version: "3.8"
services:
  backend:
    image: "cancion2able/sb-react-fullstack:30.1.2022.14.48.39"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev